# Generated by Django 2.1.3 on 2019-01-20 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CropType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Symptoms', models.TextField()),
                ('effect', models.TextField()),
                ('prevention', models.TextField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.Crop')),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=30)),
                ('water', models.CharField(max_length=30)),
                ('avg_temp', models.CharField(max_length=10)),
                ('stability', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SoilTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('phosporus', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('potassium', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('nitrogen', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('sulfate', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('boron', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('copper', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('iron', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('zinc', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('magnesium', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.Land')),
            ],
        ),
        migrations.CreateModel(
            name='SoilType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Procedure', models.TextField()),
                ('quantity', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=30)),
                ('items', models.TextField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.Disease')),
            ],
        ),
        migrations.CreateModel(
            name='Sun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Varity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
                ('min_temp', models.IntegerField()),
                ('max_temp', models.IntegerField()),
                ('month_plant', models.CharField(max_length=30)),
                ('cultivation', models.TextField()),
                ('harvest', models.TextField()),
                ('soil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.SoilType')),
                ('sun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.Sun')),
            ],
        ),
        migrations.AddField(
            model_name='land',
            name='soil_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.SoilType'),
        ),
        migrations.AddField(
            model_name='land',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
