# Generated by Django 2.1.3 on 2019-01-20 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='crop_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crop.CropType'),
        ),
        migrations.AddField(
            model_name='varity',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crop.Crop'),
        ),
        migrations.AlterField(
            model_name='land',
            name='stability',
            field=models.CharField(max_length=10),
        ),
    ]
