# Generated by Django 2.1.3 on 2019-02-28 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0002_auto_20190120_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Zoning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=30)),
                ('water', models.CharField(max_length=30)),
                ('Subregion', models.CharField(max_length=10)),
                ('soil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.SoilType')),
            ],
        ),
    ]
