# Generated by Django 2.1.3 on 2019-02-28 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0003_ph_zoning'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='cultivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='harvest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='max_temp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='min_temp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='month_plant',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='soil_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crop.SoilType'),
        ),
        migrations.AddField(
            model_name='crop',
            name='sun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crop.Sun'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
