# Generated by Django 2.1.3 on 2019-02-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0005_crop_ph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='month_plant',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
