# Generated by Django 2.1.3 on 2019-02-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0006_auto_20190228_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='water',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='varity',
            name='water',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
