# Generated by Django 2.1.3 on 2019-03-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0007_auto_20190228_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='ph_max',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='crop',
            name='ph_min',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
