# Generated by Django 2.1.3 on 2019-03-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0009_land_ph'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='pincode',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
