# Generated by Django 2.1.3 on 2019-03-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0012_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='utm_medium',
        ),
    ]
