# Generated by Django 2.1.3 on 2019-03-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0017_auto_20190303_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
